-- ============================================================================
-- resources.lua -- resource detection support: catalog IO, tier verdicts,
-- sighting binds, the unknown queue, matched-mesh capture and the
-- resources.html panel. Extracted verbatim from main.lua (history there).
-- The tolerant scorer itself still lives in main.lua's onrender3d handler;
-- it is scheduled for replacement by the fingerprint-v2 matcher, which will
-- be built HERE.
-- ============================================================================
-- Loaded with require("resources")({ ... deps ... }); interface on SET.res.
-- cell_at is an accessor (main rebinds rooms_by_cell per frame);
-- world_room_to_grid / is_room_body pass by value (assigned once).
-- Classification runs through RES.classify: exact v1 key, else the v2
-- identity matcher (phase 3); the v2 rejection memo is module-internal.
return function (deps)
local bolt = require("bolt")
local SET, S             = deps.SET, deps.S
local world_room_to_grid = deps.world_room_to_grid
local is_room_body       = deps.is_room_body
local cell_at            = deps.cell_at
local unix_now           = deps.unix_now

local RES_TILE_UNITS = 512   -- world units per game tile (mirrors main.lua)
local RES = {}
SET.res = RES

-- DINOS (overhaul phase 5). All tiers are one animated mesh at ~3012 verts --
-- pose-varying, so exact-pose prints have near-zero recall -- and tier is
-- carried ONLY by body colour. Detection is the vertex count (clean gate:
-- nothing non-dino is within +-6 of 3012). Tier is nearest-labelled-body-
-- colour, ADVISORY ONLY: it labels + highlights but NEVER binds parity,
-- because the bonus/no-inf colour margin is tight (~26 L1 at T7/T9, and T8
-- is unseen) -- too close to survive lighting for a binding decision. The
-- reference table (data/dino_colors.txt, median vertex RGB per tier from
-- labelled captures) is regenerated by tools/dino-colors.py; NO colour is
-- ever named in code -- classification is pure distance to your prints.
local DINO_N, DINO_NW = 3012, 6
local DINO_ADVISORY_MAX = 55   -- nearest-ref L1 beyond this -> tier unknown
local dino_refs = {}           -- tier -> {r, g, b}
do
  local raw = SET.load_or_seed("dino_colors.txt") or ""
  for line in raw:gmatch("[^\r\n]+") do
    local t, r, g, b = line:match("^%s*(%d+)%s*|%s*(%d+),(%d+),(%d+)")
    if t then dino_refs[tonumber(t)] = { tonumber(r), tonumber(g), tonumber(b) } end
  end
end

-- Median vertex colour over a 32-vert spread, matched to the nearest tier
-- reference. Returns (tier, dist) or nil; tier is nil when the match is
-- beyond DINO_ADVISORY_MAX (an un-referenced tier -- T5/T6/T8 today).
local function dino_tier(event, n)
  if next(dino_refs) == nil then return nil end
  local K, rs, gs, bs = 32, {}, {}, {}
  for i = 1, K do
    local idx = math.max(1, math.min(n, math.floor(i * n / (K + 1))))
    local ok, r, g, b = pcall(event.vertexcolour, event, idx)
    if ok and r then
      rs[#rs + 1] = math.floor(r * 255 + 0.5)
      gs[#gs + 1] = math.floor(g * 255 + 0.5)
      bs[#bs + 1] = math.floor(b * 255 + 0.5)
    end
  end
  if #rs < 8 then return nil end
  table.sort(rs); table.sort(gs); table.sort(bs)
  local m = math.floor(#rs / 2) + 1
  local cr, cg, cb = rs[m], gs[m], bs[m]
  local best, bd = nil, math.huge
  for tier, ref in pairs(dino_refs) do
    local d = math.abs(cr - ref[1]) + math.abs(cg - ref[2]) + math.abs(cb - ref[3])
    if d < bd then bd, best = d, tier end
  end
  if bd > DINO_ADVISORY_MAX then return nil end
  return best, bd
end

local resource_browser
local open_resource_browser, close_resource_browser
local _res_msg_last, _matches_msg_last
-- Queue freeze (panel button): while set, the queue list is not re-sorted,
-- resource_queue.txt is not re-dumped and no res: push goes to the panel --
-- so on-screen indexes, Lua-side preview fetches and the file on disk all
-- reference one stable ordering (the live-queue re-index trap, relearned
-- on the icon catalog, cannot bite).
local queue_frozen = false
-- Raw-file cache for resources.txt reloads. Declared up here because the v2
-- self-upgrader (below, before the catalog section) writes it after
-- appending -- a later declaration would silently split it into a global
-- write and a local read.
local last_res_raw = nil

-- Fingerprints currently banked for review -- drives the in-world pink
-- highlight so banked specimens are recognisable on sight. Seeded from
-- resource_review.txt at load (marks survive reloads); save_review adds
-- live. Clearing/archiving the bank refreshes on the next plugin load.
local review_keys = {}
do
  local raw = bolt.loadconfig("resource_review.txt")
  if raw then
    for line in raw:gmatch("[^\r\n]+") do
      local k = line:match("^KEY|(.+)$")
      if k then review_keys[k] = true end
    end
  end
end

-- Append one full-mesh entry to resource_review.txt for later review.
-- saveconfig overwrites, so this is read-modify-write; entries carry the
-- complete capture (fingerprint key, MVP, point cloud) so review sessions
-- need no re-sighting.
local function save_review(kind, label, n, wx, wy, wz, tx, tz, key, pts, mvp)
  local prior = bolt.loadconfig("resource_review.txt") or ""
  if #prior > 0 and not prior:match("\n$") then prior = prior .. "\n" end
  local block = string.format(
    "REVIEW|%d|%s|%s|n=%d|w=%d,%d,%d|t=%d,%d\nKEY|%s\nMVP|%s\nPTS|%s\n\n",
    unix_now and unix_now() or 0, kind, label, n, wx, wy, wz, tx, tz,
    key or "?", mvp or "", pts or "")
  bolt.saveconfig("resource_review.txt", prior .. block)
  if key then review_keys[key] = true end
end

-- Forward-declared so the resource browser's onmessage handler (attached at
-- creation time) can see the tables that get populated later in the file.
local resources_learned = {}
local last_ign_res_raw = nil
local last_dumped_list = {}
-- Populated every classified render, drained each dump_resource_queue tick and
-- shipped to the panel as JSON for the Matches tab.
local current_matches = {}
local last_dumped_matches_list = {}
-- Per-fingerprint pts / mvp cache for classified resources so the Matches tab
-- can preview them without re-capturing every frame. First sighting fills it;
-- subsequent renders skip the capture cost.
local resources_matched_seen = {}   -- key -> { pts, mvp, name, tier, n }

-- Max tier per resource-type suffix. If tier < max - 1 -> bonus verdict.
-- Missing types skip inference silently.
local resource_type_max = {}
do
  local raw = SET.load_or_seed("resource_types.txt")
  for ln in raw:gmatch("[^\r\n]+") do
    local t, m = ln:match("^%s*(%w+)%s*|%s*(%d+)%s*$")
    if t and m then resource_type_max[t] = tonumber(m) end
  end
end

-- Parse a resource icon name into (type, tier). Convention: t<N>_<type>.
local function resource_verdict(name)
  -- Catalog uses UPPERCASE (T10_ORE) plus variant suffixes (T4_TREE_2).
  -- Lowercase, then match "t<N>_<letters>" so variants collapse to their
  -- base type and non-tier names (FISHING_SPOT, LARGE_CHEST) don't match.
  local n = name:lower()
  local tier, rtype = n:match("^t(%d+)_(%a+)")
  if not tier then return nil end
  tier = tonumber(tier)
  local max = resource_type_max[rtype]
  if not max then return nil end
  if tier < max - 1 then return "bonus" end
  return nil                     -- top two tiers: no inference
end

-- Bind a resource model to the room it stands in. Sightings are STICKY (only a
-- floor wipe clears them), so a bad binding is permanent and silently poisons
-- parity forever after -- hence the guards below reject rather than guess.
--
-- Sticky is CORRECT and deliberate: "this room contains a T6 ore" is a permanent
-- truth about the floor, and the model stops rendering the moment you walk away,
-- so a non-sticky store would forget every room you left. The sightings are not
-- a view of what is on screen; they are the floor's evidence log.
--
-- A sighting is only admissible if the model's coordinates land in a cell that
-- both EXISTS and is OPENED:
--   * No cell -> the derived coords are nonsense. Seen live: FISHING_SPOT bound
--     to "2,-1", which is off the top of the map entirely.
--   * Unopened cell -> impossible. You cannot see a resource through a closed
--     door, so any sighting attributed to a room you have never entered is by
--     definition a mis-binding, not evidence. Admitting one marks a room bonus
--     off a resource that isn't in it.
-- Those two catch a GROSS mis-bind, but not the dangerous one: a cell that is
-- real and opened but simply not the right one sails straight through.
--
-- COORDINATES: world_room_to_grid is the MIRROR model (gz reflects world z),
-- fixed in 2bbe5f4 and pinned by spec.py's axis tests. A stale comment here
-- used to describe the pre-fix shift model as "known broken" -- deleted
-- 2026-07-18 after verifying the shipped function is the tested mirror.
-- Cell-level half of resource binding, shared by the local detector and the
-- party-sync merge: the guards below (opened body, base invariant) must hold
-- for REMOTE sightings too -- a peer's mis-detection is as poisonous as ours.
-- `remote` suppresses re-emission so merged events can't ping-pong.
local bind_resource_cell
local function bind_resource_sighting(res_tx, res_tz, name)
  local gx, gz = world_room_to_grid(math.floor(res_tx / 16), math.floor(res_tz / 16))
  if not gx then return end
  bind_resource_cell(gx .. "," .. gz, name, false)
end
bind_resource_cell = function (ck, name, remote)
  local cell = cell_at(ck)
  if not cell then return end
  -- Opened-ness is decided by the room BODY. Key doors and skill doors need no
  -- special case: they are OVERLAYS (silver_shield, DOOR_FARMING) drawn on top
  -- of an UNOPENED_* body, so the body still reads as unopened.
  local body
  for _, n in ipairs(cell.images) do
    if is_room_body(n) then body = n; break end
  end
  if not body then
    -- Every room on the map has a body signature, so a classified cell with no
    -- body is a detection failure -- critical, and never expected. Report it
    -- instead of quietly treating it as "not opened", which would bury the real
    -- fault under a silent skip.
    SET.dev_save("resource_diag.txt",
      ("CRITICAL: cell %s has no room-body signature; images=%s\n")
      :format(ck, table.concat(cell.images, ",")))
    return
  end
  if body:sub(1, 9) == "UNOPENED_" then return end
  -- BASE NEVER HOLDS A SKILLING RESOURCE. User-confirmed invariant, not a
  -- heuristic -- the generator does not put them there. So a sighting that binds
  -- to base is a mis-DETECTION by definition, whatever the coordinates say, and
  -- admitting one is guaranteed to be wrong.
  --
  -- This is not hypothetical: it killed a floor on 2026-07-14. A ~1820-vert mesh
  -- in base (the smuggler, most likely) matched BOTH T1_TREE_4 (1815 verts) and
  -- T1_TREE_2 (1824) -- the n+-5 bucket window reaches both from 1820 -- so base
  -- was inferred bonus off a tree that does not exist, contradicting base being
  -- crit by definition.
  --
  -- CONTAINS, DOES NOT CURE. The same loose match (n+-5, cutoff 3000, versus the
  -- ground-key matcher's exact-n and 300) will mis-label meshes in ANY room; base
  -- is only the one room where we have an invariant to catch it with. Elsewhere a
  -- false T1 silently marks a real room bonus and cascades. See dg-open-bugs.
  if body == "ICON_BASE" then
    SET.dev_save("resource_diag.txt",
      ("REJECTED %s bound to base %s -- base never holds skilling resources, so\n" ..
       "this is a mis-detection. The matcher (n+-5 / cutoff 3000) is too loose.\n")
      :format(name, ck))
    return
  end
  local bag = S.resource_sightings[ck]
  if not bag then bag = {}; S.resource_sightings[ck] = bag end
  if not bag[name] then
    bag[name] = true
    if not remote and SET.sync.emit then
      SET.sync.emit({ t = "resource", c = ck, r = name })
    end
  end
end

-- ============================================================================
-- FINGERPRINT V2 (overhaul phase 2) -- permutation-invariant features.
--
-- The v1 identity (5 verts at fixed indices) breaks whenever a mesh's vertex
-- order shifts (LOD variants, section reordering in composite models) and its
-- thin sample cross-matched foreign meshes (the base smuggler wore two tree
-- labels at once). V2 characterises the mesh by AGGREGATES of a 24-vert
-- spread -- vertex count, bbox extents, mean colour, an 8-bin colour
-- histogram, a 4-bin vertical profile and mean horizontal radius -- which
-- survive reordering (a fair sample's distribution is order-free) and, for
-- the colour features, survive animation pose too (matters for dinos later).
--
-- SHADOW MODE this phase: v2 matches are computed and logged against v1's
-- verdicts (v2_shadow.txt, dev) but do NOT feed binds; the self-upgrader
-- grows the catalog from confident v1 classifications so the v2 side fills
-- through normal play. The matcher flip is phase 3, thresholds set from the
-- shadow data. Cataloging effort is explicitly cheap per the user; multiple
-- v2 fingerprints per name are the DESIGN, not a compromise.
-- ============================================================================
local V2_K = 24              -- sampled verts per fingerprint
local V2_MAX_PER_NAME = 12   -- self-upgrade cap per resource name
local V2_DEDUPE_DIST = 50    -- closer than this to an existing entry = same pose/variant
local v2_entries = {}        -- flat list: { name, tier, n, ext, mrgb, chist, vq, rad }
local v2_count_by_name = {}
local v2_cache = {}          -- v1 fingerprint key -> v2 features (per floor)
local v2_shadow_seen = {}    -- dedupe shadow-log lines per (tile|v1name)
local v2_shadow_log = ""

local function fingerprint_v2(event, n)
  local xs, ys, zs = {}, {}, {}
  local rs, gs, bs = {}, {}, {}
  for i = 1, V2_K do
    local idx = math.max(1, math.min(n, math.floor(i * n / (V2_K + 1))))
    local ok_p, p = pcall(event.vertexpoint, event, idx)
    if not ok_p or not p then return nil end
    local x, y, z = p:get()
    local ok_c, r, g, b = pcall(event.vertexcolour, event, idx)
    if not ok_c then return nil end
    xs[i], ys[i], zs[i] = x, y, z
    rs[i] = math.floor(r * 255 + 0.5)
    gs[i] = math.floor(g * 255 + 0.5)
    bs[i] = math.floor(b * 255 + 0.5)
  end
  local minx, maxx = math.huge, -math.huge
  local miny, maxy = math.huge, -math.huge
  local minz, maxz = math.huge, -math.huge
  local cx, cz = 0, 0
  local mr, mg, mb = 0, 0, 0
  local chist = { 0, 0, 0, 0, 0, 0, 0, 0 }
  for i = 1, V2_K do
    local x, y, z = xs[i], ys[i], zs[i]
    if x < minx then minx = x end
    if x > maxx then maxx = x end
    if y < miny then miny = y end
    if y > maxy then maxy = y end
    if z < minz then minz = z end
    if z > maxz then maxz = z end
    cx = cx + x; cz = cz + z
    mr = mr + rs[i]; mg = mg + gs[i]; mb = mb + bs[i]
    local bin = (rs[i] >= 128 and 4 or 0) + (gs[i] >= 128 and 2 or 0)
              + (bs[i] >= 128 and 1 or 0) + 1
    chist[bin] = chist[bin] + 1
  end
  cx, cz = cx / V2_K, cz / V2_K
  local vq = { 0, 0, 0, 0 }
  local dy = maxy - miny
  if dy < 1 then dy = 1 end
  local rad = 0
  for i = 1, V2_K do
    local q = math.min(4, 1 + math.floor((ys[i] - miny) / dy * 4))
    vq[q] = vq[q] + 1
    local dx, dz2 = xs[i] - cx, zs[i] - cz
    rad = rad + math.sqrt(dx * dx + dz2 * dz2)
  end
  return {
    n = n,
    ext = { maxx - minx, maxy - miny, maxz - minz },
    mrgb = { mr / V2_K, mg / V2_K, mb / V2_K },
    chist = chist, vq = vq, rad = rad / V2_K,
  }
end

-- Weighted L1 feature distance. Initial weights are order-of-magnitude
-- guesses; phase 3 sets them from v2_shadow.txt data the same way the v1
-- two-band cutoffs came from match_log data.
local function v2_dist(a, b)
  local d = 0
  local nmax = math.max(a.n, b.n)
  d = d + math.abs(a.n - b.n) / nmax * 400
  for i = 1, 3 do d = d + math.abs(a.ext[i] - b.ext[i]) / 8 end
  for i = 1, 3 do d = d + math.abs(a.mrgb[i] - b.mrgb[i]) * 1.5 end
  for i = 1, 8 do d = d + math.abs(a.chist[i] - b.chist[i]) * 8 end
  for i = 1, 4 do d = d + math.abs(a.vq[i] - b.vq[i]) * 6 end
  d = d + math.abs(a.rad - b.rad) / 4
  return d
end

-- Variant suffixes collapse for rivalry: T3_TREE vs T3_TREE_2 is the same
-- resource for every consumer (verdict works on the base), so confusion
-- between them is harmless and must not create ambiguity.
local function base_name(nm)
  return (nm:gsub("_%d+$", ""))
end

-- Best entry + best rival with a DIFFERENT BASE NAME across the whole v2
-- catalog (no n-bucket prefilter: the n term of the distance does that job
-- softly, which is the point -- LOD drift must not hide candidates).
local function v2_match(f)
  local best, best_d, rival, rival_d = nil, math.huge, nil, math.huge
  for _, e in ipairs(v2_entries) do
    local d = v2_dist(f, e)
    if d < best_d then
      if best and base_name(best.name) ~= base_name(e.name) then
        rival, rival_d = best, best_d
      end
      best, best_d = e, d
    elseif best and base_name(e.name) ~= base_name(best.name) and d < rival_d then
      rival, rival_d = e, d
    end
  end
  return best, best_d, rival, rival_d
end

-- IDENTITY ACCEPTANCE (phase 3, thresholds from the 2026-07-19 distance
-- matrix): a live re-sight of a cataloged mesh lands at d=0-2; the nearest
-- print of a DIFFERENT base name observed anywhere was 78; same-family
-- variants overlap cross-tier distances (41-346 vs 78-220), so v2 does NOT
-- generalise across variants -- it recognises exactly what is cataloged,
-- and every variant earns its own print (self-upgrade or one manual
-- naming). Accept = tight distance AND a clear gap to any other-base print;
-- a rival inside the floor demotes the match to display-only (never binds).
local V2_ACCEPT      = 30
local V2_RIVAL_FLOOR = 60

-- Pure decision half, exposed for spec.py: features in, verdict out.
local function v2_accept(f)
  local best, bd, rival, rd = v2_match(f)
  if not best or bd > V2_ACCEPT then return nil, bd end
  if rival and rd < V2_RIVAL_FLOOR then
    return { name = best.name, tier = best.tier, ambig = true }, bd
  end
  return { name = best.name, tier = best.tier }, bd
end

-- Rejection memo: features are a pure function of the v1 fingerprint key,
-- so a key that failed acceptance fails until the catalog changes (reload
-- or a self-upgrade append) -- cleared at both of those sites.
local v2_reject_memo = {}
-- Same deal for the tolerant v1 fallback tier (defined next to the classifier,
-- declared here so the reload/self-upgrade sites below can clear it). Holds
-- { name, tier, score, ambig } | false -- false meaning "scored, no hit".
local v1_fallback_memo = {}

local function v2_serialize(name, tier, f)
  local q = function (x) return math.floor(x + 0.5) end
  return string.format("V2|%s|%d|%d|%d,%d,%d|%d,%d,%d|%s|%s|%d",
    name, tier or 0, f.n,
    q(f.ext[1]), q(f.ext[2]), q(f.ext[3]),
    q(f.mrgb[1]), q(f.mrgb[2]), q(f.mrgb[3]),
    table.concat(f.chist, ","),
    table.concat(f.vq, ","),
    q(f.rad))
end

local function v2_parse(line)
  local name, tier, n, ext_s, mrgb_s, chist_s, vq_s, rad_s = line:match(
    "^V2|([%w_]+)|(%d+)|(%d+)|([%-%d,]+)|([%d,]+)|([%d,]+)|([%d,]+)|(%d+)$")
  if not name then return nil end
  local function nums(s)
    local out = {}
    for v in s:gmatch("[^,]+") do out[#out + 1] = tonumber(v) end
    return out
  end
  local ext, mrgb, chist, vq = nums(ext_s), nums(mrgb_s), nums(chist_s), nums(vq_s)
  if #ext ~= 3 or #mrgb ~= 3 or #chist ~= 8 or #vq ~= 4 then return nil end
  return { name = name, tier = tonumber(tier), n = tonumber(n),
           ext = ext, mrgb = mrgb, chist = chist, vq = vq, rad = tonumber(rad_s) }
end

-- SELF-UPGRADING CATALOG: a confident, unambiguous v1 classification
-- appends its v2 fingerprint under the same name -- the v2 side fills in
-- through normal play, and the 82 existing v1 entries never need manual
-- re-cataloging. Deduped by distance so a parked player doesn't append the
-- same pose 60x/second; capped per name as a runaway guard.
local function v2_self_upgrade(name, tier, f)
  -- DINOS ARE EXCLUDED until the dino phase: one shared mesh across tiers,
  -- tier carried ONLY by colour, positions vary with animation pose
  -- (confirmed 2026-07-19: T9/T4 review captures, identical n=3012 and
  -- sample indices, different colours). The current v2 features cannot be
  -- trusted to separate tiers there; v1 exact-pose prints stay safe because
  -- a byte-identical key cannot be the wrong dino.
  if name:find("_DINO", 1, true) then return end
  if (v2_count_by_name[name] or 0) >= V2_MAX_PER_NAME then return end
  for _, e in ipairs(v2_entries) do
    if e.name == name and v2_dist(f, e) < V2_DEDUPE_DIST then return end
  end
  local entry = { name = name, tier = tier or 0, n = f.n,
                  ext = f.ext, mrgb = f.mrgb, chist = f.chist,
                  vq = f.vq, rad = f.rad }
  v2_entries[#v2_entries + 1] = entry
  v2_count_by_name[name] = (v2_count_by_name[name] or 0) + 1
  -- Only the REJECT memo is cleared: a new print may rescue a mesh that matched
  -- nothing. Meshes that already have a v1-fallback verdict keep it -- a new
  -- print of the same name would only re-derive the same name, and wiping that
  -- memo too made every append re-classify every mesh in view, which is O(M^2)
  -- on walking into a room full of previously-dark resources.
  v2_reject_memo = {}
  -- last_res_raw is kept exactly in sync (below, and by reload_resources), so
  -- use it instead of re-reading a ~30KB file on every append.
  local raw = last_res_raw or SET.load_or_seed("resources.txt") or ""
  if #raw > 0 and not raw:match("\n$") then raw = raw .. "\n" end
  raw = raw .. v2_serialize(name, tier, f) .. "\n"
  bolt.saveconfig("resources.txt", raw)
  last_res_raw = raw   -- in-memory state already updated; skip the reparse
end

-- Shadow observation: compute v2 for this mesh (memoised on the v1 key --
-- static objects cost one sample, not 60/s), maybe self-upgrade, and log
-- v1-vs-v2 agreement. v1name == nil means v1 drew a blank (the queue path):
-- a confident v2 hit there is exactly the coverage the overhaul is after.
local function v2_observe(event, key, n, v1name, v1tier, v1score, v1ambig, tx, tz)
  local f = v2_cache[key]
  if f == nil then
    f = fingerprint_v2(event, n) or false
    v2_cache[key] = f
  end
  if not f then return end
  if v1name and not v1ambig and v1score and v1score <= 100 then
    v2_self_upgrade(v1name, v1tier, f)
  end
  if not SET.DEV then return end
  local sk = tx .. "," .. tz .. "|" .. tostring(v1name)
  if v2_shadow_seen[sk] then return end
  v2_shadow_seen[sk] = true
  local best, bd, rival, rd = v2_match(f)
  -- Provisional accept band for LOG CLASSIFICATION only (first floor's data:
  -- same-object re-match = 0, foreign meshes vs an ore print = 713+; the
  -- phase-3 threshold will be set from accumulated data, this just keeps the
  -- log readable). Nearest-neighbor without a band mislabeled every unknown
  -- as the closest of a 3-entry catalog.
  local V2_LOG_BAND = 300
  local agree
  if not best then agree = "V2-EMPTY"
  elseif not v1name then
    -- Only an in-band hit is a coverage candidate; far misses are noise and
    -- movers walking across tiles would flood the log with them.
    if bd > V2_LOG_BAND then return end
    agree = "V1-MISS"
  elseif best.name == v1name then agree = "AGREE"
  else agree = "DISAGREE" end
  v2_shadow_log = (v2_shadow_log .. string.format(
    "%-9s tile=%d,%-4d n=%-5d v1=%-16s s=%-6s v2=%-16s d=%-6d rival=%s\n",
    agree, tx, tz, n, tostring(v1name), tostring(v1score),
    best and best.name or "(none)", best and math.floor(bd + 0.5) or -1,
    rival and string.format("%s:%d", rival.name, math.floor(rd + 0.5)) or "(none)"))
    :sub(-12000)
  SET.dev_save("v2_shadow.txt", v2_shadow_log)
end

local RES_LEARNED_TTL   = 300           -- frames before an unseen entry expires
-- Unknown-queue vertexcount bounds, driven by the panel's verts slider. Default
-- min 1500 (decals/sparkles below that are noise); max 5000 = fingerprint cap.
local queue_vmin, queue_vmax = 1500, 5000
-- SHOW LARGE (panel toggle): lifts the fingerprint's >5000-vert reject, the
-- >4-tile bbox reject, and the queue's upper bound, so big/spread meshes (large
-- puzzle apparatus, scenery) can be surfaced. Noisy -- meant to be toggled on
-- only while hunting a specific large model.
local show_large = false

local resources_catalog = {}   -- fingerprint_key -> { name, tier }
local resources_ignored = {}   -- fingerprint_key -> true
-- resources_learned and last_ign_res_raw are forward-declared at the top of
-- the file so the resource browser's onmessage handler can close over them.
local function fingerprint_resource(event)
  local n = event:vertexcount()
  if n < 4 then return nil end
  if not show_large and n > 5000 then return nil end   -- lifted by SHOW LARGE
  local step = math.max(1, math.floor(n / 6))
  local parts = { tostring(n) }
  -- Local-space bbox from the 5 samples; used to reject anything that spans
  -- more than one game tile in X or Z.
  local x_min, x_max = math.huge, -math.huge
  local z_min, z_max = math.huge, -math.huge
  for i = 1, 5 do
    local idx = math.min(n, i * step)
    local ok_p, p = pcall(event.vertexpoint, event, idx)
    if not ok_p or not p then return nil end
    local x, y, z = p:get()
    local ok_c, r, g, b = pcall(event.vertexcolour, event, idx)
    if not ok_c then return nil end
    if x < x_min then x_min = x end
    if x > x_max then x_max = x end
    if z < z_min then z_min = z end
    if z > z_max then z_max = z end
    parts[#parts + 1] = string.format("%d,%d,%d,%d,%d,%d,%d", idx,
      math.floor(x + 0.5), math.floor(y + 0.5), math.floor(z + 0.5),
      math.floor(r * 255 + 0.5), math.floor(g * 255 + 0.5), math.floor(b * 255 + 0.5))
  end
  -- Relaxed from 1 tile to 4 tiles so large multi-part meshes (dinos, etc.)
  -- can still enter the queue. Very-wide scenery still gets rejected -- unless
  -- SHOW LARGE is on, which lifts this bbox reject too.
  if not show_large
     and ((x_max - x_min) > RES_TILE_UNITS * 4 or (z_max - z_min) > RES_TILE_UNITS * 4) then
    return nil
  end
  return table.concat(parts, "|"), n
end

-- Parsed catalog entry: keeps the 5 sample verts as numbers so we can do
-- tolerant matching (positions may drift a few units, vertex colours may
-- get lighting-tinted). Index by vertex count for cheap candidate lookup.
local resources_by_n = {}   -- n -> list of parsed catalog entries

local function parse_catalog_verts(rest)
  local n_str, tail = rest:match("^(%d+)|(.+)$")
  local n = tonumber(n_str)
  if not n then return nil end
  local verts = {}
  for chunk in tail:gmatch("[^|]+") do
    local ix, x, y, z, r, g, b = chunk:match(
      "^(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+)$")
    if ix then
      verts[#verts + 1] = {
        idx = tonumber(ix),
        x = tonumber(x), y = tonumber(y), z = tonumber(z),
        r = tonumber(r), g = tonumber(g), b = tonumber(b),
      }
    end
  end
  return n, verts
end

local function reload_resources()
  local raw = SET.load_or_seed("resources.txt")
  if raw == last_res_raw then return end
  last_res_raw = raw
  resources_catalog = {}
  resources_by_n = {}
  v2_entries = {}
  v2_count_by_name = {}
  v2_reject_memo = {}     -- catalog changed: rejected meshes get a fresh chance
  v1_fallback_memo = {}
  if raw then
    for line in raw:gmatch("[^\r\n]+") do
      if not line:match("^%s*#") and not line:match("^%s*$") then
        local v2e = v2_parse(line)
        if v2e then
          v2_entries[#v2_entries + 1] = v2e
          v2_count_by_name[v2e.name] = (v2_count_by_name[v2e.name] or 0) + 1
        else
        local name, tier, rest = line:match("^%s*([%w_]+)|(%d+)|(.+)$")
        if name and tier and rest then
          local n, verts = parse_catalog_verts(rest)
          if n and verts then
            -- Pre-sort verts by y for the order-invariant scorer path. Sorting
            -- once at load beats sorting every candidate every frame.
            local verts_sorted = { verts[1], verts[2], verts[3], verts[4], verts[5] }
            table.sort(verts_sorted, function (a, b) return a.y < b.y end)
            local entry = { name = name, tier = tonumber(tier), n = n,
                            verts = verts, verts_sorted = verts_sorted }
            resources_by_n[n] = resources_by_n[n] or {}
            resources_by_n[n][#resources_by_n[n] + 1] = entry
            -- Keep the exact-key map as a fast-path when the fingerprint is byte-identical.
            resources_catalog[rest] = { name = name, tier = tonumber(tier) }
          end
        end
        end
      end
    end
  end
end

local function reload_ignored_resources()
  local raw = SET.load_or_seed("resource_ignored.txt")
  if raw == last_ign_res_raw then return end
  last_ign_res_raw = raw
  resources_ignored = {}
  if raw then
    for line in raw:gmatch("[^\r\n]+") do
      if not line:match("^%s*#") and not line:match("^%s*$") then
        resources_ignored[line] = true
      end
    end
  end
end
reload_resources()
reload_ignored_resources()

-- ---- Guardian doors ---------------------------------------------------------
-- 3D-mesh prints kept SEPARATE from resources (guardian_doors.txt). One print
-- per floor type, so a live guardian matches exactly one, strictly. Matched by
-- the same 5-vert local fingerprint used for keys (position-invariant).
local guardian_by_n = {}   -- n -> { {name, verts_sorted}, ... }
local function reload_guardians()
  local raw = SET.load_or_seed("guardian_doors.txt")
  guardian_by_n = {}
  if raw then
    for line in raw:gmatch("[^\r\n]+") do
      if not line:match("^%s*#") and not line:match("^%s*$") then
        local name, _tier, rest = line:match("^%s*([%w_]+)|(%d+)|(.+)$")
        if name and rest then
          local n, verts = parse_catalog_verts(rest)
          if n and verts and #verts >= 5 then
            local vs = { verts[1], verts[2], verts[3], verts[4], verts[5] }
            table.sort(vs, function (a, b) return a.y < b.y end)
            guardian_by_n[n] = guardian_by_n[n] or {}
            table.insert(guardian_by_n[n], { name = name, verts = vs })
          end
        end
      end
    end
  end
end
reload_guardians()

-- True if a mesh's vertexcount could be a guardian (cheap gate before sampling).
RES.guardian_n = function (n) return guardian_by_n[n] ~= nil end
-- Strict fingerprint match: returns the guardian name (e.g. GUARDIAN_DOOR_3) or
-- nil. Same metric as the ground-key matcher (pos L1 + summed colour), tight
-- cutoff -- a real guardian re-sight scores ~0 against its own floor's print.
RES.guardian_hit = function (event, n)
  local bucket = guardian_by_n[n]
  if not bucket then return nil end
  local step = math.max(1, math.floor(n / 6))
  local live = {}
  for i = 1, 5 do
    local idx = math.min(n, i * step)
    local ok_p, p = pcall(event.vertexpoint, event, idx)
    if not ok_p or not p then return nil end
    local x, y, z = p:get()
    local ok_c, r, g, b = pcall(event.vertexcolour, event, idx)
    if not ok_c then return nil end
    live[i] = {
      x = math.floor(x + 0.5), y = math.floor(y + 0.5), z = math.floor(z + 0.5),
      r = math.floor(r * 255 + 0.5), g = math.floor(g * 255 + 0.5), b = math.floor(b * 255 + 0.5),
    }
  end
  table.sort(live, function (a, b) return a.y < b.y end)
  local best, bestname = math.huge, nil
  for _, e in ipairs(bucket) do
    local pos, col = 0, 0
    for i = 1, 5 do
      local ev, lv = e.verts[i], live[i]
      pos = pos + math.abs(ev.x - lv.x) + math.abs(ev.y - lv.y) + math.abs(ev.z - lv.z)
      col = col + math.abs(ev.r - lv.r) + math.abs(ev.g - lv.g) + math.abs(ev.b - lv.b)
    end
    local s = pos + 2 * col
    if s < best then best, bestname = s, e.name end
  end
  if best <= 300 then return bestname, best end
  return nil, best
end

-- ---- Puzzle ghosts ---------------------------------------------------------
-- Two attackable NPCs in a puzzle room share ONE mesh (n=1428) and differ only
-- in baked vertex brightness: the DARK one is the vulnerable GOOD_GHOST, the
-- light ones are BAD_GHOSTs, and the game rotates which ghost is vulnerable on
-- a timer. NOT resources -- main.lua detects them ahead of the resource path
-- and returns, so they never queue, never bind a sighting and never reach the
-- parity evidence. The only consumer is the in-world highlight.
--
-- Identity is deliberately POSITION-FREE. These animate, so sampled vertex
-- positions drift with the pose; the two captures we have are byte-identical in
-- position only because both were caught mid-idle. What is stable is the
-- vertexcount plus a SCALE-INVARIANT colour signature -- every sampled vert is
-- neutral (r == g) with a slight blue lift (b = r + ~3). That survives the
-- lighting scale separating the two states (the observed pair differ by a
-- uniform x1.22), which is exactly the thing we must not normalise away: the
-- brightness IS the good/bad tell.
local ghost_ns = {}                      -- vertexcount -> true
local ghost_lum_good, ghost_lum_bad      -- cataloged mean luminances
local function reload_ghosts()
  local raw = SET.load_or_seed("ghosts.txt")
  ghost_ns = {}
  ghost_lum_good, ghost_lum_bad = nil, nil
  if not raw then return end
  for line in raw:gmatch("[^\r\n]+") do
    if not line:match("^%s*#") and not line:match("^%s*$") then
      local name, _tier, rest = line:match("^%s*([%w_]+)|(%d+)|(.+)$")
      if name and rest then
        local n, verts = parse_catalog_verts(rest)
        if n and verts and #verts == 5 then
          ghost_ns[n] = true
          local sum = 0
          for _, v in ipairs(verts) do sum = sum + (v.r + v.g + v.b) / 3 end
          if name == "GOOD_GHOST" then ghost_lum_good = sum / 5
          elseif name == "BAD_GHOST" then ghost_lum_bad = sum / 5 end
        end
      end
    end
  end
end
reload_ghosts()

RES.ghost_n = function (n) return ghost_ns[n] == true end

-- Mean sampled luminance, or nil if this mesh does not carry the ghost colour
-- signature. The caller compares luminance ACROSS the ghosts on screen to pick
-- the vulnerable one; the absolute split below is only the one-ghost fallback.
RES.ghost_lum = function (event, n)
  local step = math.max(1, math.floor(n / 6))
  local sum = 0
  for i = 1, 5 do
    local idx = math.min(n, i * step)
    local ok, r, g, b = pcall(event.vertexcolour, event, idx)
    if not ok then return nil end
    r = math.floor(r * 255 + 0.5)
    g = math.floor(g * 255 + 0.5)
    b = math.floor(b * 255 + 0.5)
    if math.abs(r - g) > 4 or (b - r) < 0 or (b - r) > 8 then return nil end
    sum = sum + (r + g + b) / 3
  end
  return sum / 5
end

-- Midpoint of the two cataloged luminances, or nil if the catalog lacks either.
RES.ghost_split = function ()
  if ghost_lum_good and ghost_lum_bad then
    return (ghost_lum_good + ghost_lum_bad) / 2
  end
  return nil
end

-- ---- Tolerant v1 fallback (sits BELOW v2) ----------------------------------
-- v2 recognises exactly what has a V2 print, and 40 of the catalog's 88 names
-- have none -- they were cataloged as v1 lines, and the self-upgrader can only
-- mint a V2 print from a CONFIDENT v1 classification, which the phase-3 flip
-- removed. Those names went dark: exact-key or nothing, so a single LSB of
-- lighting drift dropped them into the unknown queue with no highlight, and
-- they could never earn the v2 print that would fix them. This tier breaks
-- that deadlock; the names convert to v2 through normal play from here.
--
-- Tightened against the failure that retired the old v1 matcher. That one ran
-- an n+-5 candidate window with cutoff 3000 (see the mis-detection note on
-- learn_resource above). Measured over the current catalog:
--
--   variant vs its own base (T6_ORE/T6_ORE_2)     6-10   harmless, base_name collapses these
--   true re-sight of the same print               4-54   MUST be caught
--   nearest DIFFERENT base name within n+-5       1492   MUST NOT be caught
--
-- so cutoff 3000 sat twice the collision floor and was guaranteed to bind
-- foreign meshes. Exact-n with a 300 cutoff sits 5x under the floor and 5x
-- over the worst true re-sight. Checked against 526 explicitly-ignored
-- non-resource meshes: zero genuine false matches, and 90% of them share no
-- vertex count with any catalog entry at all -- the exact-n gate, not the
-- cutoff, is what does the work here.
local function v1_fallback(key, n)
  -- Below this, meshes carry too little signal to match tolerantly: the only
  -- catalog entry under it is FISHING_SPOT (9 verts, five flat-grey samples)
  -- and 9-vert quads are everywhere in a scene. It has a V2 print, so the
  -- exclusion costs nothing. 1500 is the queue's own admission floor.
  local MIN_N = 1500
  local BIND  = 100   -- <= this: a real match; binds and feeds the upgrader
  local SHOW  = 300   -- <= this: display-only (ambig), never reaches parity
  if n < MIN_N then return nil end
  local bucket = resources_by_n[n]
  if not bucket then return nil end
  -- Scored straight off the fingerprint key -- it already holds the 5 sampled
  -- verts, so this costs no bolt calls. Sorted by y like every other matcher
  -- here, so vertex-order drift cannot swing the result.
  local _, live = parse_catalog_verts(key)
  if not live or #live ~= 5 then return nil end
  table.sort(live, function (a, b) return a.y < b.y end)
  local best, best_score = nil, math.huge
  for _, e in ipairs(bucket) do
    local ev_list = e.verts_sorted
    local pos, col, ok_all = 0, 0, true
    for i = 1, 5 do
      local ev, lv = ev_list[i], live[i]
      if not ev then ok_all = false; break end
      pos = pos + math.abs(ev.x - lv.x) + math.abs(ev.y - lv.y) + math.abs(ev.z - lv.z)
      col = col + math.abs(ev.r - lv.r) + math.abs(ev.g - lv.g) + math.abs(ev.b - lv.b)
    end
    local s = pos + 2 * col
    if ok_all and s < best_score then best, best_score = e, s end
  end
  if not best or best_score > SHOW then return nil end
  return best, best_score, best_score > BIND
end

-- THE classifier (phase 3). Exact v1 fingerprint first (byte-identical key
-- = free and ground truth by construction), then the v2 identity matcher,
-- then the tolerant v1 fallback for names v2 has no print for.
-- Returns (entry, score, ambig) or nil; score is 0 for exact hits and the
-- v2 distance (or the v1 fallback score) otherwise, feeding the Matches tab
-- unchanged.
function RES.classify(event, key, n)
  local exact = resources_catalog[key]
  if exact then
    -- Dinos NEVER bind, even on an exact-pose hit -- force advisory (ambig).
    return exact, 0, (exact.name and exact.name:find("_DINO", 1, true)) ~= nil
  end
  -- DINO detection: vertex-count gate, colour->tier (advisory, never binds).
  if n >= DINO_N - DINO_NW and n <= DINO_N + DINO_NW then
    local tier = dino_tier(event, n)
    if tier then return { name = "T" .. tier .. "_DINO", tier = tier }, 0, true end
    return { name = "DINO", tier = 0 }, 0, true   -- dino, tier not yet referenced
  end
  -- Misses land in v2_reject_memo (both tiers declined); hits land in
  -- v1_fallback_memo. Both are cleared together whenever the catalog changes,
  -- so the split costs nothing and keeps each memo's meaning exact.
  if v2_reject_memo[key] then return nil end
  local fb = v1_fallback_memo[key]
  if fb then return { name = fb.name, tier = fb.tier }, fb.score, fb.ambig end
  local f = v2_cache[key]
  if f == nil then
    f = fingerprint_v2(event, n) or false
    v2_cache[key] = f
  end
  -- A failed v2 sample (f == false) still falls through to the v1 tier: that
  -- one scores off the key, which we already have, so it needs no sampling.
  local hit, bd
  if f then hit, bd = v2_accept(f) end
  if hit then
    return { name = hit.name, tier = hit.tier }, bd, hit.ambig or false
  end
  local e, s, ambig = v1_fallback(key, n)
  if e then
    v1_fallback_memo[key] = { name = e.name, tier = e.tier, score = s, ambig = ambig }
    return { name = e.name, tier = e.tier }, s, ambig
  end
  v2_reject_memo[key] = true
  return nil
end

-- Full-mesh capture for panel previews: local-space verts + client-side MVP,
-- shared by the matched-seen path and the unknown queue (was two verbatim
-- copies inline in the render handler).
-- Full-mesh preview capture is ONLY needed to draw a mesh in the resource
-- panel. It costs up to ~10k bolt calls per unique mesh (5000 verts x 2), so
-- when the panel is closed we skip it entirely -- detection/binding never use
-- pts/mvp, only the preview does. main.lua toggles this with the panel.
local capture_enabled = false
local function capture_mesh(event, n)
  if not capture_enabled then return "", "" end
  local pts = {}
  -- Full capture: the fingerprint gate upstream already rejects n > 5000,
  -- so this cap never truncates -- review marks bank the COMPLETE mesh
  -- (was 3000, which cut the top off 4k-vert marks).
  local pts_n = math.min(n, show_large and 20000 or 5000)
  for vi = 1, pts_n do
    local ok_p, p = pcall(event.vertexpoint, event, vi)
    if not ok_p or not p then break end
    local vx, vy, vz = p:get()
    local ok_c, r, g, b = pcall(event.vertexcolour, event, vi)
    if not ok_c then break end
    pts[#pts + 1] = string.format("%d,%d,%d,%d,%d,%d",
      math.floor(vx + 0.5), math.floor(vy + 0.5), math.floor(vz + 0.5),
      math.floor(r * 255 + 0.5), math.floor(g * 255 + 0.5), math.floor(b * 255 + 0.5))
  end
  local mvp_str = ""
  local ok_vp, vp = pcall(event.viewprojmatrix, event)
  local ok_mm, mm = pcall(event.modelmatrix, event)
  if ok_vp and vp and ok_mm and mm then
    local v = { vp:get() }
    local m = { mm:get() }
    -- Column-major multiplication: OUT = VP * M
    local out = {}
    for col = 0, 3 do
      for row = 0, 3 do
        local sum = 0
        for k = 0, 3 do
          sum = sum + v[k * 4 + row + 1] * m[col * 4 + k + 1]
        end
        out[#out + 1] = tostring(sum)
      end
    end
    mvp_str = table.concat(out, ",")
  end
  return table.concat(pts, ";"), mvp_str
end

-- Matched-mesh record: preview capture (once per fingerprint) + the live
-- Matches-tab entry (keyed by tile so multiple instances all show).
function RES.record_match(event, key, n, name, tier, btx, btz, wx, wz, score, dist2, ambig)
  local seen = resources_matched_seen[key]
  if not seen then
    local pts, mvp_str = capture_mesh(event, n)
    resources_matched_seen[key] = {
      pts = pts, mvp = mvp_str, name = name, tier = tier, n = n,
    }
  elseif capture_enabled and (seen.pts == nil or seen.pts == "") then
    -- Backfill: first matched while the panel was closed (capture off) -> pts
    -- empty. Re-capture now the panel is open so the Matches preview renders.
    seen.pts, seen.mvp = capture_mesh(event, n)
  end
  local mkey = btx .. "," .. btz .. "|" .. name
  current_matches[mkey] = {
    key = key, name = name, tier = tier,
    tx = btx, tz = btz,
    wx = math.floor(wx + 0.5), wz = math.floor(wz + 0.5),
    score = score, dist2 = dist2,
    -- Sticky TTL (frames), refreshed on every re-sight. The Matches list is
    -- rebuilt from current_matches; without a TTL it was wiped every dump tick
    -- (~4/s) and only refilled by scan frames (~5Hz), so any match not caught
    -- in a given dump window blinked out -- the panel flicker. Aged in
    -- tick_resources; entries survive gaps between sightings.
    ttl = RES_LEARNED_TTL,
  }
  v2_observe(event, key, n, name, tier, score, ambig, btx, btz)
end

-- Unknown-mesh queue admission (low-poly filtered; sticky until TTL).
function RES.queue_unknown(event, key, n, wx, wy, wz, dist2)
  if resources_ignored[key] then return end
  -- Vertexcount window from the panel's verts slider (default 1500..5000).
  -- Below the min is usually decals/sparkles/projectiles; the panel can lower it
  -- to surface small puzzle props. Cataloged low-poly resources (FISHING_SPOT
  -- n=9) classify in the handler before this runs.
  if n < queue_vmin then return end
  if not show_large and n > queue_vmax then return end   -- upper bound off under SHOW LARGE
  local tx = math.floor(wx / RES_TILE_UNITS)
  local tz = math.floor(wz / RES_TILE_UNITS)
  -- v1 drew a blank on this mesh: a confident v2 hit here is exactly the
  -- coverage gain the overhaul is after -- logged as V1-MISS in the shadow.
  v2_observe(event, key, n, nil, nil, nil, nil, tx, tz)
  local entry = resources_learned[key]
  if not entry then
    local pts, mvp_str = capture_mesh(event, n)
    resources_learned[key] = {
      key = key, n = n,
      wx = math.floor(wx + 0.5),
      wy = math.floor(wy + 0.5),
      wz = math.floor(wz + 0.5),
      tx = tx, tz = tz,
      dist2 = dist2, ttl = RES_LEARNED_TTL,
      pts = pts, mvp = mvp_str,
    }
  else
    entry.dist2 = dist2
    entry.wx = math.floor(wx + 0.5)
    entry.wy = math.floor(wy + 0.5)
    entry.wz = math.floor(wz + 0.5)
    entry.tx = tx; entry.tz = tz
    entry.ttl = RES_LEARNED_TTL
    -- Backfill the preview: an entry first queued while the panel was CLOSED
    -- has empty pts/mvp (capture was gated off for perf). Once the panel opens
    -- capture_enabled flips true, so re-capture on the next sighting -- else a
    -- resource walked past before opening the panel previews blank forever.
    -- capture_mesh returns "" while disabled, so this stays a no-op then.
    if capture_enabled and (entry.pts == nil or entry.pts == "") then
      entry.pts, entry.mvp = capture_mesh(event, n)
    end
  end
end

local RES_PANEL_W, RES_PANEL_H = 320, 400
local res_x, res_y = 40, 640
do
  local saved = SET.get("res_panel_pos", nil)
  if saved then res_x, res_y = saved[1], saved[2] end
end
open_resource_browser = function ()
  if resource_browser then return end
  res_x, res_y = SET.clamp(res_x, res_y, RES_PANEL_W, RES_PANEL_H)
  resource_browser = bolt.createembeddedbrowser(
    res_x, res_y, RES_PANEL_W, RES_PANEL_H, "plugin://resources.html")
  resource_browser:onreposition(function (event)
    local nx, ny = event:xywh()
    SET.set("res_panel_pos", { nx, ny })
  end)
  resource_browser:onmessage(function (msg)
    -- Verts slider: set the unknown-queue vertexcount window.
    local vlo, vhi = msg:match("^vrange:(%d+),(%d+)$")
    if vlo then queue_vmin, queue_vmax = tonumber(vlo), tonumber(vhi); return end
    -- SHOW LARGE toggle: lift the >5000-vert / bbox / upper-bound rejects.
    local sl = msg:match("^show_large:(%d)$")
    if sl then show_large = (sl == "1"); return end
    -- Preview request: modal opened for queue entry #i (1-based).
    local pi = msg:match("^preview:(%d+)$")
    if pi then
      local idx = tonumber(pi)
      local e = last_dumped_list[idx]
      if e and resource_browser then
        -- Payload mirrors the icon path so the panel's triangle rasteriser can
        -- be reused:  "pts:<idx>|<sw>|<sh>|<mvp16>:<pts>"
        -- Resources don't have a real screen box, so pass a canonical 128x128
        -- viewport — MVP is scale-invariant, that just controls output res.
        resource_browser:sendmessage(string.format("pts:%d|128|128|%s:%s",
          idx, e.mvp or "", e.pts or ""))
      end
      return
    end
    -- Match preview: request full mesh data for a row in the Matches tab.
    local pmi = msg:match("^preview_match:(%d+)$")
    if pmi then
      local idx = tonumber(pmi)
      local m = last_dumped_matches_list[idx]
      local d = m and resources_matched_seen[m.key]
      if d and resource_browser then
        resource_browser:sendmessage(string.format(
          "mpts:%d|128|128|%s:%s", idx, d.mvp or "", d.pts or ""))
      end
      return
    end
    if msg == "freeze_queue" then queue_frozen = true; return end
    if msg == "unfreeze_queue" then queue_frozen = false; return end
    -- Mark-for-review: persist the previewed entry's full capture.
    local rq = msg:match("^review_queue:(%d+)$")
    if rq then
      local e = last_dumped_list[tonumber(rq)]
      if e then
        save_review("queue", "?", e.n, e.wx, e.wy or 0, e.wz,
          e.tx, e.tz, e.key, e.pts, e.mvp)
      end
      return
    end
    local rm = msg:match("^review_match:(%d+)$")
    if rm then
      local m = last_dumped_matches_list[tonumber(rm)]
      local d = m and resources_matched_seen[m.key]
      if m and d then
        save_review("match", string.format("%s:t%d", m.name, m.tier or 0),
          d.n or 0, m.wx, 0, m.wz, m.tx, m.tz, m.key, d.pts, d.mvp)
      end
      return
    end
    if msg == "ignore_all" then
      local prior = SET.load_or_seed("resource_ignored.txt") or ""
      if #prior > 0 and not prior:match("\n$") then prior = prior .. "\n" end
      local added = {}
      for k, _ in pairs(resources_learned) do added[#added + 1] = k end
      if #added > 0 then
        bolt.saveconfig("resource_ignored.txt",
          prior .. table.concat(added, "\n") .. "\n")
        last_ign_res_raw = nil
        resources_learned = {}
      end
    end
  end)
end
close_resource_browser = function ()
  if not resource_browser then return end
  resource_browser:close(); resource_browser = nil
end

-- Snapshot dump — called from onswapbuffers. Sorted by ascending distance so
-- the CLOSEST unknown to the player is always index 1. Also pushes a JSON
-- snapshot to the resource panel so the browser can render a live list.
-- last_dumped_list is forward-declared at the top of the file so the resource
-- browser's onmessage handler can see it. Overwritten below on each dump.
local function dump_resource_queue()
  -- FROZEN: list ordering, resource_queue.txt and the panel's rows all stay
  -- exactly as last dumped; only the Matches tab keeps flowing.
  if not queue_frozen then
    local list = {}
    for _, e in pairs(resources_learned) do list[#list + 1] = e end
    table.sort(list, function (a, b) return a.dist2 < b.dist2 end)
    last_dumped_list = list
    local out = {}
    for _, e in ipairs(list) do
      out[#out + 1] = string.format("%s|%d|%d|%d|%d",
        e.key, e.n, e.wx, e.wy, e.wz)
    end
    SET.dev_save("resource_queue.txt", table.concat(out, "\n") .. "\n")
  end

  if resource_browser then
    if not queue_frozen then
    local json = { "[" }
    for i, e in ipairs(last_dumped_list) do
      if i > 40 then break end
      if i > 1 then json[#json + 1] = "," end
      -- The key is n|idx,x,y,z,r,g,b|... — parse out the 5 sample verts.
      local samples = {}
      local first = true
      for chunk in e.key:gmatch("[^|]+") do
        if first then first = false else
          local ix, x, y, z, r, g, bl = chunk:match(
            "^(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+),(%-?%d+)$")
          if ix then
            samples[#samples + 1] = string.format(
              "{\"x\":%s,\"y\":%s,\"z\":%s,\"r\":%s,\"g\":%s,\"b\":%s}",
              x, y, z, r, g, bl)
          end
        end
      end
      json[#json + 1] = string.format(
        "{\"n\":%d,\"wx\":%d,\"wy\":%d,\"wz\":%d,\"tx\":%d,\"tz\":%d,\"v\":[%s]}",
        e.n, e.wx, e.wy, e.wz, e.tx, e.tz, table.concat(samples, ","))
    end
    json[#json + 1] = "]"
    local res_msg = "res:" .. table.concat(json)
    if res_msg ~= _res_msg_last then
      _res_msg_last = res_msg
      resource_browser:sendmessage(res_msg)
    end
    end   -- not queue_frozen

    -- Ship the Matches tab payload: everything the classifier hit since the
    -- last dump, with position and match score. Sort by score ascending so
    -- lowest-confidence (highest-score) matches float to the top of the list.
    local mlist = {}
    for _, m in pairs(current_matches) do mlist[#mlist + 1] = m end
    table.sort(mlist, function (a, b)
      if a.score ~= b.score then return a.score > b.score end   -- weakest first
      if a.dist2 ~= b.dist2 then return a.dist2 < b.dist2 end
      return a.name < b.name
    end)
    last_dumped_matches_list = mlist
    local mjson = { "[" }
    for i, m in ipairs(mlist) do
      if i > 80 then break end
      if i > 1 then mjson[#mjson + 1] = "," end
      -- score can be math.huge for exact-key hits that skipped the scorer? no —
      -- we init to math.huge but only push a match when classified is non-nil,
      -- and either 0 (exact) or a finite scorer result is set. Still guard.
      local score_s = (m.score == math.huge) and "-1" or tostring(math.floor(m.score + 0.5))
      local has_pts = resources_matched_seen[m.key] and (resources_matched_seen[m.key].pts or "") ~= ""
      mjson[#mjson + 1] = string.format(
        "{\"name\":\"%s\",\"tier\":%d,\"tx\":%d,\"tz\":%d,\"score\":%s,\"live\":%s}",
        m.name, m.tier, m.tx, m.tz, score_s, has_pts and "true" or "false")
    end
    mjson[#mjson + 1] = "]"
    local matches_msg = "matches:" .. table.concat(mjson)
    if matches_msg ~= _matches_msg_last then
      _matches_msg_last = matches_msg
      resource_browser:sendmessage(matches_msg)
    end
    -- NOT wiped here: current_matches is now a sticky, TTL-aged list (see
    -- record_match / tick_resources) so the Matches tab holds steady between
    -- the ~5Hz scans instead of flickering. Old code reset it every dump.
  end
end

-- Age out stale entries.
local function tick_resources()
  local dead = {}
  for k, e in pairs(resources_learned) do
    e.ttl = e.ttl - 1
    if e.ttl <= 0 then dead[#dead + 1] = k end
  end
  for _, k in ipairs(dead) do resources_learned[k] = nil end
  -- Matches age the same way (sticky list; see record_match).
  local mdead = {}
  for k, m in pairs(current_matches) do
    m.ttl = (m.ttl or 0) - 1
    if m.ttl <= 0 then mdead[#mdead + 1] = k end
  end
  for _, k in ipairs(mdead) do current_matches[k] = nil end
end

-- ---- Public interface (main reaches everything through SET.res).
RES.fingerprint   = fingerprint_resource
RES.exact         = function (key) return resources_catalog[key] end
RES.is_ignored    = function (key) return resources_ignored[key] == true end
RES.by_n          = function (n) return resources_by_n[n] end
RES.catalog_ns    = function ()
  local out = {}
  for k in pairs(resources_by_n) do out[#out + 1] = tostring(k) end
  table.sort(out)
  return out
end
RES.has_queue     = function () return next(resources_learned) ~= nil end
RES.queue_entries = function () return resources_learned end
-- Pink means PENDING review: banked and not yet cataloged. Cataloging an
-- entry (export, queue naming, self-upgrade) turns its highlight off on
-- the next catalog reload -- the same rule the review page uses to hide
-- resolved entries.
RES.is_reviewed   = function (key)
  return review_keys[key] == true and resources_catalog[key] == nil
end
RES.verdict       = resource_verdict
RES.bind_cell     = function (ck, name, remote) return bind_resource_cell(ck, name, remote) end
RES.bind_sighting = bind_resource_sighting
RES.reload_all    = function () reload_resources(); reload_ignored_resources(); reload_guardians(); reload_ghosts() end
RES.tick          = tick_resources
RES.dump_queue    = dump_resource_queue
RES.open_panel    = function () open_resource_browser() end
RES.close_panel   = function () close_resource_browser() end
-- Per-floor v2 state: the fingerprint memo keys on v1 fingerprints (stable
-- per object within a floor) and the shadow-log dedupe keys on tiles --
-- both are floor-scoped, so main's wipe_floor_state calls this.
RES.floor_wipe    = function ()
  v2_cache = {}
  v2_shadow_seen = {}
  -- Matches are sticky (TTL-aged) now, so clear them on a floor change or the
  -- new floor briefly shows the previous floor's matches until they age out.
  current_matches = {}
  _matches_msg_last = nil
end
-- Enable/disable full-mesh preview capture (main.lua ties this to the resource
-- panel being open). Off = no pts/mvp captured, saving ~10k bolt calls/mesh.
RES.set_capture   = function (on) capture_enabled = on and true or false end
-- Pure v2 internals for spec.py (and offline tooling): parse/serialize/
-- dist/accept plus the live entries table so tests can seed fixtures.
RES.v2 = {
  parse = v2_parse, serialize = v2_serialize, dist = v2_dist,
  accept = v2_accept, entries = function () return v2_entries end,
}
return RES
end
